name: MacOS Build
on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.5.0' # Senin sürümüne göre ayarla
        host: 'mac'
        
    - name: Build
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_PREFIX_PATH=$QT_ROOT_DIR
        make
        # .app dosyasını sıkıştır
        zip -r TelgrafApp-Mac.zip TelgrafApp.app
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: TelgrafApp-MacOS
        path: build/TelgrafApp-Mac.zip